### ISSUE TITLE
Please add a more specific home page

### ISSUE THREAD

**Issue by pcav** [planetlabs/qgis-planet-plugin#1]
rather than a generic one.
Thanks.

**Comment by sarasafavi** [comment]
hi @pcav - the documentation & download page https://developers.planet.com/integrations/ is linked from README.md; specifically, the docs for this plugin are found at https://developers.planet.com/docs/integrations/qgis/ and the download link is https://go.planet.com/qgis ... can you be more specific on what you're looking for?

**Comment by pcav** [comment]
The website https://www.planet.com/ is generic, not specifically relating to the plugin. One of the ones you mentioned looks better to me.
Thanks.

**Comment by sarasafavi** [comment]
Closing as the aforementioned documentation link is included in README.rst already; planet.com is not designated as this plugin's "home page" anywhere in the readme or related documentation.

**Comment by pcav** [comment]
Please do not close tickets unless you are sure. The homepage is defined in:
https://github.com/planetlabs/qgis-planet-plugin/blob/master/planet_explorer/metadata.txt

**Comment by KevinWhalen** [comment]
Extending on @pcav, line 40 of the metadata has the homepage as only <planet.com>, but the currently packaged version deployed to the QGIS plugin repository links to <developers.planet.com/docs/integrations/qgis/>. I do remember hitting planet.com root a few times while searching for things, but that may have been while looking at the GeoServer Explorer.
