### ISSUE TITLE
Defined AOI is systematically invalid 

### ISSUE THREAD

**Issue by loicdtx** [planetlabs/qgis-planet-plugin#18]
Whenever I try to define an AOI to search the daily imagery catalog I get a `WARNING    AOI GeoJSON geometry invalid`, and no spatial filter is applied to the search. This happens with all AOI input methods (direct drawing using the plugin's widgets, paste of valid geojson feature, ...).

I'm using the version 2.1 of the plugin

## System settings:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

QGIS version | 3.10.9-A Coruña | QGIS code branch | Release 3.10
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.3 (Ubuntu 12.3-1build1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Ubuntu 20.10

</body></html>

**Comment by volaya** [comment]
This is fixed here:

https://github.com/planetlabs/qgis-planet-plugin/commit/35be310ea2cdbe6b2c3a30d9910f35029e685dc3
