### ISSUE TITLE
RFC: Better widget for showing basemaps?

### ISSUE THREAD

**Issue by john-dupuy** [planetlabs/qgis-planet-plugin#33]
When loading basemaps, the dropdown that displays quickly becomes unwieldy as there are so many of them. This is particularly clear when you look at a "Cadence" of "All" and try to select a series. 

Does Qt provide a widget that would allow a nice search or "Show more" button so that ALL the basemaps don't show in the dropdown?

**Comment by vermeulendivan** [comment]
@john-dupuy Noted the same problem while looking at other possible problems with the plugin. Its almost impossible to find what you are looking for. 'show more' will also just end up with an extremely long list the more a user click on 'show more', so the problem will persist. Won't it be better to split it all into groups?

Add a group drop down parameter:
![image](https://user-images.githubusercontent.com/79740955/209102044-d9c85752-6599-4ede-a90a-d57d7f0b947d.png)

Just a quick example of basemaps which can be grouped together:
![image](https://user-images.githubusercontent.com/79740955/209101425-eea265f6-bd07-495b-b099-1ecea536d318.png)

Therefore the user can then select the group, and the series which will then only consist of the basemaps in that group. I hope that makes sense.
Noted that this is assigned to Volaya, but I can do this?

**Comment by vermeulendivan** [comment]
There are more than 3000 layers in this list.

**Comment by john-dupuy** [comment]
I like this suggestion. I reassigned the issue to you. 

This UX problem is actually also in planet.com/explorer. Afaik it mostly impacts planet employees as they are the only ones that have access to this many basemaps. Most regular customers only have access to a handful of basemaps. 

@astrong19 curious if you think this approach is worth pursuing?

**Comment by vermeulendivan** [comment]
@john-dupuy I have put together a table for suggested grouping for the basemaps, I will discuss it with Asa at today's meeting.

**Comment by joferkington** [comment]
Just to confirm, no customers have access to a large number of basemap series. (I'm the person who handles basemap generation, btw.)

Almost all of what you're seeing are unusual/custom series that only a single customer would have access to.  

Standard series (things multiple customers have access to / the "select basemap" product) will have "subscription" in the name (and additional tags in the API, though you won't be able to see those in your API responses).  Standard series are shared between customers and there's one series for each type of basemap and cadence.  Custom series have different processing for the same interval/etc, so for custom, there's one series per customer.

No customer will have access to more than a couple dozen series at most. Academic customers have access to more series than anyone else (they get access to all select basemap products), but it's still only a couple of dozen for them.

I'd recommend not trying to solve a problem that doesn't actually exist for end users.  Adding grouping will negatively impact all end users as it will be an additional level of hierarchy for no reason and make selecting a series more difficult.

Furthermore, the suggested grouping _isn't_ actually grouping related series, just for clarity!!  It will group completely unrelated things in many cases.

**Comment by john-dupuy** [comment]
Thank you for chiming in @joferkington - I agree we should not try to solve a problem that doesn't exist for end users. I'm going to close this one. We can revisit if it's a situation that actually impacts our users.
