### ISSUE TITLE
Plugin ignores QGIS proxy configuration.

### ISSUE THREAD

**Issue by mirandadam** [planetlabs/qgis-planet-plugin#5]
Package inspection reveals that plugin tries to contact api.planet.com directly instead of going through the corporate proxy as configured in the QGIS proxy settings.

The problem appears as a failed connection attemp when trying to provide login credentials in the plugin window.
O.S. version: Windows 10
QGIS version: 3.10 and 3.14

Under Ubuntu Linux, the plugin uses the environment variables. In my case, it successfully connected even when I disabled the proxy in QGIS. Therefore even though the problem (ignoring proxy settings) is still there, Linux users are less likely to experience any issue, as long as environment variables are set correctly.

Please look into this. It is affecting tens of users behind our corporate firewall all over the country. I am referring this issue to our Planet.com services provider in Brazil to expedite a solution.

Best regards!
--Daniel

**Comment by carolinaplanet** [comment]
Hi Daniel,
Thanks for bribing this to our attention.
I am taking a look at this with our engineering team. 
We will get back ASAP.

Cheers, 
Carolina

**Comment by bosth** [comment]
Hi Daniel,

We have committed a fix (see #6) and this will be in the next release of the plugin. Please let us know if you have any further problems!

**Comment by MattFerraro** [comment]
We expect to publish the next release within a few days, to incorporate this fix

**Comment by mirandadam** [comment]
See comment in #6. No-proxy rules are still being ignored.
