### ISSUE TITLE
CI test errors against pull requests

### ISSUE THREAD

**Issue by Samweli** [planetlabs/qgis-planet-plugin#62]
Current CI workflow raises errors when it runs agains pull requests made by users who don't have full access to the plugin repository.

The following errors have appeared in the recent submitted PRs.

- Failing due to long running time, some tests matrix timeout at 3mins and 28/29 secs - [https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3375040820/jobs/5601295038#step:3:204](https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3375040820/jobs/5601295038#step:3:204)
- QGIS 3.22 docker image doesn't contain `qgis` executable hence its related matrix fails - [https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:6:9](https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:6:9)
- Missing `py` package, in some PRs running docker tests throws an exception about not finding the `py` module - [https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:3:176](https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:3:176)
- No access to planet credentials - [https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:3:237](https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:3:237)

**Comment by john-dupuy** [comment]
Hi @Samweli - thanks for the bug report. 

> Failing due to long running time, some tests matrix timeout at 3mins and 28/29 secs - https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3375040820/jobs/5601295038#step:3:204

I believe this is because of the last issue "No access to planet credentials" 

> Missing py package, in some PRs running docker tests throws an exception about not finding the py module - https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:3:176

It looks like there was an update that broke the install step - investigating.

**Comment by john-dupuy** [comment]
https://github.com/planetlabs/qgis-planet-plugin/pull/65 addresses:
- Missing py package, in some PRs running docker tests throws an exception about not finding the py module - https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:3:176
- QGIS 3.22 docker image doesn't contain qgis executable hence its related matrix fails - https://github.com/planetlabs/qgis-planet-plugin/actions/runs/3376868140/jobs/5605108944#step:6:9

**Comment by Samweli** [comment]
> #65 addresses:

Thanks @john-dupuy

**Comment by Samweli** [comment]
Closed via https://github.com/planetlabs/qgis-planet-plugin/pull/65
