### ISSUE TITLE
Cannot login using a provided account.

### ISSUE THREAD

**Issue by Jeremy-Prior** [planetlabs/qgis-planet-plugin#89]
Trying to log in using a provided testing account fails continuously on both Windows and Linux:
![PID7_LoginFails](https://user-images.githubusercontent.com/100694811/207012435-aeffc56f-a83a-4d13-a1f7-ca6ef174964d.gif)

Unsure what is causing this issue.

@vermeulendivan @Samweli

**Comment by vermeulendivan** [comment]
@Jeremy-Prior I can login using the account you used here. John stated that there were a outage (see comments here https://github.com/planetlabs/qgis-planet-plugin/issues/87). If you are also no longer having an issue, we can close this ticket.

**Comment by Jeremy-Prior** [comment]
@vermeulendivan I can log in using the account now.

**Comment by vermeulendivan** [comment]
@Jeremy-Prior Thanks!
